### ISSUE TITLE
好像没有封装为npm package

### ISSUE THREAD

**Issue by billwing** [leancloud/js-analytics-sdk#8]
看了下，貌似这个也是不能用的：https://www.npmjs.com/package/leancloud-analytics
如果Web这边使用analytics，岂不是要在页面暴露`appId`和`appKey`？

**Comment by wangxiao** [comment]
这个库官方没有发布到 npm；
页面暴露 appId 和 appKey 相关的安全问题，请参考 https://leancloud.cn/docs/data_security.html
